[package]
name = "corenn-node"
publish = false
version = "0.3.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
libcorenn = { version = "0.3.1", path = "../libcorenn" }
neon = "1.1.1"
