[package]
name = "libroxanne"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
croaring = "2.1.0"
itertools = "0.13.0"
linfa = "0.7.0"
linfa-clustering = { version = "0.7.0", features = ["serde"] }
linfa-nn = "0.7.0"
ndarray = "0.15" # linfa uses 0.15.
num-traits = "0.2.19"
ordered-float = "4.3.0"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.128"
