[package]
name = "libroxanne"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
croaring = "2.1.0"
itertools = "0.13.0"
ordered-float = "4.3.0"
rand = "0.8.5"

[dev-dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
