[package]
name = "roxanne-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.19", features = ["derive"] }
libroxanne = { path = "../libroxanne", features = ["verbose"] }
ndarray = "0.15"
rayon = "1.10.0"
