name: Build and publish Python package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# How cross compilation works with PyO3/maturin-action:
# - For Linux targets, it uses Docker.
# - For other targets, it runs on the host (Docker mostly only supports Linux containers).
# - On Windows, the action appears to just use the host binary. Cross compilation to a different arch doesn't seem to be yet supported.
# - On macOS, the action appears to be able to target aarch64 just fine despite running on an Intel Mac.
# - We don't need to set up Rust, the action will do so itself.
# - We don't need to set up Python:
#   - On macOS, the action auto finds all versions: https://github.com/PyO3/maturin-action/blob/a3013db91b2ef2e51420cfe99ee619c8e72a17e6/src/index.ts#L732
#   - On Linux, a Docker container is used which has its own Rust, Python, etc.
#   - On Windows, we use the "generate-import-lib" feature on pyo3: https://www.maturin.rs/distribution#cross-compile-to-windows
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-2022]
        target: [x86_64, aarch64]
        python:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
        exclude:
          # Building for Windows aarch64 isn't ready yet.
          - os: windows-2022
            target: aarch64
    steps:
      - uses: actions/checkout@v1

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          # https://github.com/PyO3/maturin-action/issues/49#issuecomment-1166242843
          args: --release --sdist --strip -m ./corenn-py/Cargo.toml -i ${{ matrix.python }}
          sccache: true
          rust-toolchain: nightly
          rustup-components: rustfmt
          before-script-linux: |
            # Install gcc, g++, and clang for both Debian/Ubuntu and RHEL/CentOS
            if command -v apt-get &>/dev/null; then
              apt-get update
              apt-get -yq install gcc g++ clang
            elif command -v dnf &>/dev/null; then
              dnf -y install gcc gcc-c++ clang
            elif command -v yum &>/dev/null; then
              yum -y install gcc gcc-c++ clang
            else
              echo "No supported package manager found for installing gcc, g++, and clang." >&2
              exit 1
            fi

      - name: Install Python build tools (macOS)
        if: runner.os == 'macOS'
        run: sudo pip install --upgrade twine
      - name: Install Python build tools (Linux, Windows)
        if: runner.os != 'macOS'
        run: pip install --upgrade twine

      - name: Pack and publish package
        shell: bash
        working-directory: ./corenn-py
        run: |
          cat << 'EOF' > "$HOME/.pypirc"
          [pypi]
          username = __token__
          password = ${{ secrets.PYPI_API_TOKEN }}
          EOF
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            # For idempotency, ignore any existing built wheels that have already been successfully uploaded.
            twine upload --skip-existing ../target/wheels/*
          else
            ls -al ../target/wheels/*
          fi
